apiVersion: v1
kind: Pod
metadata:
  name: app-secret-env
spec:
  containers:
  - name: redis-container
    image: redis:latest
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: mysecrets
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecrets
          key: password